### PR TITLE
new static() is safe with a final class

### PR DESCRIPTION
**Pull request by szepeviktor**
@nikolaposa

### CODE REVIEW

**Comment by nikolaposa** [comment]
I do not quite understand what benefit this change introduces, as `new static`(late static binding) has no point in case of `final` class. 

Besides, making a class `final` is BC break as some consumers of the library may have extended it, so I have to be careful during release management.

**Comment by szepeviktor** [comment]
I've used @phpstan and it told me to do so: https://twitter.com/phpstan/status/1162376299039678464?lang=en

**Comment by nikolaposa** [comment]
Do you know what `new static` is used for to begin with? Consider this:
```
class Options
{
    public static function fromArray(array $options)
    {
        return new static($options);
    }
}

class CustomOptions extends Options 
{
}

$customOptions = CustomOptions::fromArray();

assertInstanceOf(CustomOptions::class, $customOptions);
```

If `self` was used instead inside `fromArray()`, `$customOptions` would be an instance of `Options`, which is not intended behaviour.

Therefore, I still do not understand the point you are trying to make. Could you elaborate why do you think that every class that use `new static` must be final, because that doesn't make any sense to me?

**Comment by szepeviktor** [comment]
I see. So you want `fromArray()` to return an instance of the current class even if it is a child of `Options`.
I think @ondrejmirtes knows why he implemented this rule.

**Comment by nikolaposa** [comment]
Thanks for posting the link to that tweet by the way, 👍 I'll ask the same question there.

**Comment by ondrejmirtes** [comment]
The solution to this error message is either:

1) Realizing that `new static()` isn't supposed to be there and changing it to `new self()`.
2) Making the class final - at which point `new static()` can also be changed to `new self()`.
3) Or making the constructor final. Which leaves the class open to inheritance but closes the potential bug when using `new static()`.

All of them are BC breaks (although they are fixing potential bugs) so should be done carefully in library contexts.

**Comment by ondrejmirtes** [comment]
And if it isn't obvious, the bug this rule prevents looks like this: https://3v4l.org/dP6BP

**Comment by nikolaposa** [comment]
That makes much more sense, thank you. Constructor _can_ be marked as `final` in order to prevent such bugs in extending libraries. Leaving class opened for extension and customization was intentional.

**Pull request closed without merging**
